# LiquidatorHub Configuration
# Demonstrating YAML configuration capabilities

project:
  name: "LiquidatorHub Profile"
  version: "1.0.0"
  description: "Comprehensive showcase of development capabilities"
  author: "LiquidatorHub"
  
environment:
  development:
    debug: true
    log_level: "DEBUG"
    database:
      host: "localhost"
      port: 5432
      name: "dev_db"
    
  production:
    debug: false
    log_level: "INFO"
    database:
      host: "${DB_HOST}"
      port: "${DB_PORT}"
      name: "${DB_NAME}"

skills:
  programming_languages:
    - name: "Python"
      proficiency: "Expert"
      years_experience: 5
      frameworks: ["Django", "Flask", "FastAPI", "Pandas", "NumPy"]
      
    - name: "JavaScript/TypeScript"
      proficiency: "Expert" 
      years_experience: 4
      frameworks: ["React", "Vue.js", "Node.js", "Express"]
      
    - name: "Java"
      proficiency: "Advanced"
      years_experience: 3
      frameworks: ["Spring Boot", "Hibernate", "Maven"]
      
    - name: "Go"
      proficiency: "Intermediate"
      years_experience: 2
      frameworks: ["Gin", "Echo", "Gorilla"]

  technologies:
    cloud_platforms:
      - "AWS (EC2, S3, Lambda, RDS)"
      - "Google Cloud Platform"
      - "Microsoft Azure"
      
    databases:
      - "PostgreSQL"
      - "MongoDB"
      - "Redis"
      - "MySQL"
      - "InfluxDB"
      
    devops_tools:
      - "Docker"
      - "Kubernetes"
      - "Jenkins"
      - "GitHub Actions"
      - "Terraform"
      
    monitoring:
      - "Prometheus"
      - "Grafana"
      - "ELK Stack"
      - "Datadog"

capabilities:
  can_do:
    - "Full-stack web development"
    - "API design and implementation"
    - "Database design and optimization"
    - "Cloud infrastructure setup"
    - "CI/CD pipeline configuration"
    - "Performance optimization"
    - "Security implementation"
    - "Code reviews and mentoring"
    - "Technical documentation"
    - "Problem-solving and debugging"
    
  specializations:
    - "Microservices architecture"
    - "Real-time applications"
    - "Data processing pipelines"
    - "Machine learning integration"
    - "Mobile app development"
    - "API gateway design"
    
contact:
  github: "https://github.com/LiquidatorHub"
  email: "contact@liquidatorhub.dev"
  timezone: "UTC"
  available_for:
    - "Open source contributions"
    - "Technical consulting"
    - "Code reviews"
    - "Mentoring"
    - "Collaborative projects"

philosophy:
  code_quality: "Clean, readable, and maintainable code is paramount"
  learning: "Continuous learning and adaptation to new technologies"
  collaboration: "Great software is built by great teams"
  impact: "Technology should solve real problems and create value"